//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostArk.Discord.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ru_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LostArk.Discord.Bot.Resources.Localization.ru-ru", typeof(Localization_ru_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить персонажа.
        /// </summary>
        internal static string AddCharacter {
            get {
                return ResourceManager.GetString("AddCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аркана.
        /// </summary>
        internal static string arcana {
            get {
                return ResourceManager.GetString("arcana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватар.
        /// </summary>
        internal static string avatar {
            get {
                return ResourceManager.GetString("avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бард.
        /// </summary>
        internal static string bard {
            get {
                return ResourceManager.GetString("bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Берсерк.
        /// </summary>
        internal static string berserker {
            get {
                return ResourceManager.GetString("berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить язык.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить часовой пояс.
        /// </summary>
        internal static string ChangeTimezone {
            get {
                return ResourceManager.GetString("ChangeTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персонажи:.
        /// </summary>
        internal static string CharsListTitle {
            get {
                return ResourceManager.GetString("CharsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите класс:.
        /// </summary>
        internal static string ChoseClass {
            get {
                return ResourceManager.GetString("ChoseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клинок смерти.
        /// </summary>
        internal static string deathblade {
            get {
                return ResourceManager.GetString("deathblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string DeleteCharacter {
            get {
                return ResourceManager.GetString("DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Охотник на демонов.
        /// </summary>
        internal static string demonhunter {
            get {
                return ResourceManager.GetString("demonhunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сокрушитель.
        /// </summary>
        internal static string destroyer {
            get {
                return ResourceManager.GetString("destroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дуалист.
        /// </summary>
        internal static string dualist {
            get {
                return ResourceManager.GetString("dualist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string EditCharacter {
            get {
                return ResourceManager.GetString("EditCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фурия.
        /// </summary>
        internal static string fury {
            get {
                return ResourceManager.GetString("fury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страж.
        /// </summary>
        internal static string gunlancer {
            get {
                return ResourceManager.GetString("gunlancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Охотница на демонов.
        /// </summary>
        internal static string gunslinger {
            get {
                return ResourceManager.GetString("gunslinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастер копья.
        /// </summary>
        internal static string lancemaster {
            get {
                return ResourceManager.GetString("lancemaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык изменен.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Механист.
        /// </summary>
        internal static string mechanist {
            get {
                return ResourceManager.GetString("mechanist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паладин.
        /// </summary>
        internal static string paladin {
            get {
                return ResourceManager.GetString("paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейд создан.
        /// </summary>
        internal static string RaidCreatedMessageTemplate {
            get {
                return ResourceManager.GetString("RaidCreatedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейнджер.
        /// </summary>
        internal static string ranger {
            get {
                return ResourceManager.GetString("ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жнец.
        /// </summary>
        internal static string reaper {
            get {
                return ResourceManager.GetString("reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствую тебя искатель,
        ///Я :angel:Беатрис:angel: - твой проводник в мире :crossed_swords: Lost Ark.
        ///Я буду держать тебя в курсе событий на сервере {0}.
        ///Так же могу напоминать о внутри игровых событиях на которые ты подпишешься.
        ///Искатель, начни с регитрации своих персонажей в меню ниже.
        ///Успехов тебе и пусть всегда с тобой будет идти благословение Руфеона!.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агент С.К.А.У.Т..
        /// </summary>
        internal static string scouter {
            get {
                return ResourceManager.GetString("scouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать голосовые комнаты.
        /// </summary>
        internal static string SetupBossRaidChannelsConfirm {
            get {
                return ResourceManager.GetString("SetupBossRaidChannelsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосовые комнаты для боссов.
        /// </summary>
        internal static string SetupBossRaidChannelsDescription {
            get {
                return ResourceManager.GetString("SetupBossRaidChannelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочешь что бы я создала голосовые комнаты для боссов?.
        /// </summary>
        internal static string SetupBossRaidChannelsTitle {
            get {
                return ResourceManager.GetString("SetupBossRaidChannelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для начала выбери роль, 
        ///которая будет управлять моими настройками.
        ///Только пользователь с этой ролью сможет выполнть дальнейшую настройку.
        /// </summary>
        internal static string SetupChoseRole {
            get {
                return ResourceManager.GetString("SetupChoseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбери роль.
        /// </summary>
        internal static string SetupChoseRolePlaceholder {
            get {
                return ResourceManager.GetString("SetupChoseRolePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать роли.
        /// </summary>
        internal static string SetupClassRolesCreateButton {
            get {
                return ResourceManager.GetString("SetupClassRolesCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите, чтобы я настроила роли классов.
        ///Роли пользователей будут назначены, когда они настроят своих персонажей..
        /// </summary>
        internal static string SetupClassRolesDescription {
            get {
                return ResourceManager.GetString("SetupClassRolesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка ролей.
        /// </summary>
        internal static string SetupClassRolesTitle {
            get {
                return ResourceManager.GetString("SetupClassRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string SetupConinueButton {
            get {
                return ResourceManager.GetString("SetupConinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствую тебя искатель,
        ///Я помогу тебе настроить сервер.
        /// </summary>
        internal static string SetupDescription {
            get {
                return ResourceManager.GetString("SetupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка сервера.
        /// </summary>
        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли текущего пользователя не соотвествуют: {0}.
        /// </summary>
        internal static string SetupUserDoesNotHaveAnyRole {
            get {
                return ResourceManager.GetString("SetupUserDoesNotHaveAnyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбраны неверные роли.
        /// </summary>
        internal static string SetupWrongUserRoleTitle {
            get {
                return ResourceManager.GetString("SetupWrongUserRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чародейка.
        /// </summary>
        internal static string sorceress {
            get {
                return ResourceManager.GetString("sorceress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ки-мастер.
        /// </summary>
        internal static string soulmaster {
            get {
                return ResourceManager.GetString("soulmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призывательница.
        /// </summary>
        internal static string summoner {
            get {
                return ResourceManager.GetString("summoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тайгон.
        /// </summary>
        internal static string taigon {
            get {
                return ResourceManager.GetString("taigon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовой пояс.
        /// </summary>
        internal static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
    }
}
