//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostArk.Discord.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LostArk.Discord.Bot.Resources.Localization.en-us", typeof(Localization_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Character.
        /// </summary>
        internal static string AddCharacter {
            get {
                return ResourceManager.GetString("AddCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane.
        /// </summary>
        internal static string arcana {
            get {
                return ResourceManager.GetString("arcana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string avatar {
            get {
                return ResourceManager.GetString("avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        internal static string bard {
            get {
                return ResourceManager.GetString("bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berserker.
        /// </summary>
        internal static string berserker {
            get {
                return ResourceManager.GetString("berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change timezone.
        /// </summary>
        internal static string ChangeTimezone {
            get {
                return ResourceManager.GetString("ChangeTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charecters list:.
        /// </summary>
        internal static string CharsListTitle {
            get {
                return ResourceManager.GetString("CharsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a class.
        /// </summary>
        internal static string ChoseClass {
            get {
                return ResourceManager.GetString("ChoseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathblade.
        /// </summary>
        internal static string deathblade {
            get {
                return ResourceManager.GetString("deathblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteCharacter {
            get {
                return ResourceManager.GetString("DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonhunter.
        /// </summary>
        internal static string demonhunter {
            get {
                return ResourceManager.GetString("demonhunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer.
        /// </summary>
        internal static string destroyer {
            get {
                return ResourceManager.GetString("destroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infighter.
        /// </summary>
        internal static string dualist {
            get {
                return ResourceManager.GetString("dualist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditCharacter {
            get {
                return ResourceManager.GetString("EditCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonic.
        /// </summary>
        internal static string fury {
            get {
                return ResourceManager.GetString("fury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunlancer.
        /// </summary>
        internal static string gunlancer {
            get {
                return ResourceManager.GetString("gunlancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunslinger.
        /// </summary>
        internal static string gunslinger {
            get {
                return ResourceManager.GetString("gunslinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lance Master.
        /// </summary>
        internal static string lancemaster {
            get {
                return ResourceManager.GetString("lancemaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artillerist.
        /// </summary>
        internal static string mechanist {
            get {
                return ResourceManager.GetString("mechanist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        internal static string paladin {
            get {
                return ResourceManager.GetString("paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid created.
        /// </summary>
        internal static string RaidCreatedMessageTemplate {
            get {
                return ResourceManager.GetString("RaidCreatedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpshooter.
        /// </summary>
        internal static string ranger {
            get {
                return ResourceManager.GetString("ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaper.
        /// </summary>
        internal static string reaper {
            get {
                return ResourceManager.GetString("reaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello seeker,
        ///I am :angel:Beatrice:angel: - your guide in the world :crossed_swords: Lost Ark.
        ///I&apos;ll keep you posted on what&apos;s happening on server {0}.
        ///I can also remind you of in-game events that you subscribe to.
        ///Seeker, start by registering your characters in the menu below.
        ///Good luck to you and may the blessing of Rufeon always go with you!.
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scouter.
        /// </summary>
        internal static string scouter {
            get {
                return ResourceManager.GetString("scouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voice rooms.
        /// </summary>
        internal static string SetupBossRaidChannelsConfirm {
            get {
                return ResourceManager.GetString("SetupBossRaidChannelsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create boss raid voice-rooms.
        /// </summary>
        internal static string SetupBossRaidChannelsDescription {
            get {
                return ResourceManager.GetString("SetupBossRaidChannelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me create voice-rooms for Raid bosses.
        /// </summary>
        internal static string SetupBossRaidChannelsTitle {
            get {
                return ResourceManager.GetString("SetupBossRaidChannelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First you should select admin role 
        ///for controlling my settings.
        ///Only user with this role can coninue setup.
        /// </summary>
        internal static string SetupChoseRole {
            get {
                return ResourceManager.GetString("SetupChoseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose role.
        /// </summary>
        internal static string SetupChoseRolePlaceholder {
            get {
                return ResourceManager.GetString("SetupChoseRolePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Roles.
        /// </summary>
        internal static string SetupClassRolesCreateButton {
            get {
                return ResourceManager.GetString("SetupClassRolesCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me setup class roles.
        ///User roles will be assigned when they setup their characters.
        /// </summary>
        internal static string SetupClassRolesDescription {
            get {
                return ResourceManager.GetString("SetupClassRolesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Roles.
        /// </summary>
        internal static string SetupClassRolesTitle {
            get {
                return ResourceManager.GetString("SetupClassRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string SetupConinueButton {
            get {
                return ResourceManager.GetString("SetupConinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome seeker, 
        ///I
        ///
        /// will gide you through the server setup process.
        /// </summary>
        internal static string SetupDescription {
            get {
                return ResourceManager.GetString("SetupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server SetUp.
        /// </summary>
        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user rolees doesn&apos;t match: {0}.
        /// </summary>
        internal static string SetupUserDoesNotHaveAnyRole {
            get {
                return ResourceManager.GetString("SetupUserDoesNotHaveAnyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Roles Selected.
        /// </summary>
        internal static string SetupWrongUserRoleTitle {
            get {
                return ResourceManager.GetString("SetupWrongUserRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorceress.
        /// </summary>
        internal static string sorceress {
            get {
                return ResourceManager.GetString("sorceress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulfist.
        /// </summary>
        internal static string soulmaster {
            get {
                return ResourceManager.GetString("soulmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner.
        /// </summary>
        internal static string summoner {
            get {
                return ResourceManager.GetString("summoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Striker.
        /// </summary>
        internal static string taigon {
            get {
                return ResourceManager.GetString("taigon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
    }
}
